### ISSUE TITLE
Update UpSet CSS not to pollute global style

### ISSUE THREAD

**Issue by jeffbaumes** [Kitware/candela#101]
Currently UpSet defines these (and probably more), they should be made to only be used within UpSet element.

```css
a:link, a:visited {
    color: black;
}
* {
    margin: 0;
    padding: 0;
}
```
